### ISSUE TITLE
List of users who liked the article

### ISSUE THREAD

**Issue by xdisplayx** [cybercog/laravel-likeable#19]
Hi, could you shed some light on how to get the list of users who liked the article.

Thanks for your help, greetings.

**Comment by antonkomarev** [comment]
Hello @xdisplayx! Good question. There is no such functionality implemented at this moment.
If you have an idea how to implement it without hardcoding user model - Pull Requests are welcome!

Hardcoded example:
```php
$likersIds = $entity->likes->pluck('user_id');
$likers = User::whereIn('id', $likersIds)->get();
```

**Comment by xdisplayx** [comment]
Thanks for your example, it was very useful.

**Comment by antonkomarev** [comment]
@xdisplayx I've added a PR #20 with this feature to be able to use it out of the box, but it wouldn't be merged until 3.0 release. Need more time to think about better way to implement it and API of the package.

**Comment by xdisplayx** [comment]
Gracias por su ayuda, yo de momento he creado unos acesores en el modelo de articulos mediante su ejemplo. Por lo demas de poca ayuda puedo ser, no entiendo GitHub y aunque lo intento no lo logro entender y el que este solo en ingles no ayuda nada.

Gracias de nuevo por su ayuda que me permitio seguir aprendiendo algo mas.

PD: Y el traductor de google aun ayuda menos.


Thanks for your help, I have for the moment created acesores in the model of articles by example. For the rest of little help I can be, I do not understand GitHub and although I try not to understand and that this alone in English does not help anything.

Thanks again for your help that allowed me to continue learning something else.
PS: And the Google translator still helps less.

**Comment by antonkomarev** [comment]
You are welcome! Keep learning and build awesome software!

**Comment by antonkomarev** [comment]
Implemented in v3 of the package.
