### ISSUE TITLE
Sorting by likes doesn't sort by the different between likes and dislikes

### ISSUE THREAD

**Issue by sroy** [cybercog/laravel-likeable#22]
There is no way to sort by ( likes - dislikes ) that I can find currently, only by total amount of likes and total amount of dislikes.  Something to sort by likesDiffDislikesCount() would be really nice :)  I'm not experienced enough send a PR.

**Comment by antonkomarev** [comment]
Hello @sroy! Thanks for sharing your idea. I've added this feature in todo list.

**Comment by antonkomarev** [comment]
To implement this feature we will require to introduce additional table or add extra rows in `like_counter` table with additional enum type related to `likes_diff_dislikes`. Otherwise queries and sorting in runtime will be significantly slow on big databases.

**Comment by antonkomarev** [comment]
Moved to https://github.com/cybercog/laravel-love/issues/4
