### ISSUE TITLE
Unable to get liked from a collection

### ISSUE THREAD

**Issue by acidjazz** [cybercog/laravel-likeable#27]
I'm trying to get wether or not the current logged in user has liked items w/in a collection

I tried to do something like
```php
$images = Image::with('likesCounter', 'liked');
```
And I get `Call to a member function addEagerConstraints() on boolean`

If I loop through my results and hit `->liked` on each row I get a 45 query result instead of 5, is this possible at all?

**Comment by antonkomarev** [comment]
Hello, @acidjazz! `liked` is not a relation. It's a helper method which determine if model is liked. So I'm not sure it's appropriate to pass it to `with` method.

```php
$images = Image::with('likesAndDislikes')->get();

foreach ($images as $image) {
    dump($image->liked()); // Will return if current user liked entity
    dump($image->liked(4); // Will return if user with id 4 liked entity
}
```

If you don't need dislikes you can use `likes` relation.
```php
$images = Image::with('likes')->get();
```

**Comment by acidjazz** [comment]
Thanks @a-komarev, would it also be possible to add a `isliked` or `liked` scope/helper of some sort? this would help avoid a query per row when receiving likeable items with knowledge if the current user has liked them.

**Comment by antonkomarev** [comment]
Sounds interesting, but I don't have enough time to dive into this. Pull Requests are welcomed!

**Comment by acidjazz** [comment]
@a-komarev how about something like this in the Likeable Trait
```php

/**
* Collection of likes on this record by the logged in user.
*
* @return \Illuminate\Database\Eloquent\Relations\MorphMany
*/
public function isliked()
{
  return $this->likesAndDislikes()->where([
    'type_id' => LikeType::LIKE,
    'user_id' => auth()->id()
  ]);
}
```

**Comment by acidjazz** [comment]
`isLiked`? `isUserLiked` `userLikes` ? what would we name it?

**Comment by antonkomarev** [comment]
You have chosen good name in your PR. `userLikes` seems good for me, because it include like entities, and not only boolean. Prefix `is` usually means boolean return value.

**Comment by antonkomarev** [comment]
Thank you for the contribution Kevin. You was added you to the [Contributors list](https://github.com/cybercog/laravel-likeable#contributors).
I've added test cases where guest user trying to fetch likes and have thought about possible issues with not web auth guard. Have you tried to use this method in API?
We need to ensure this is working well and then I will be ready to make public v3.1 release.

**Comment by acidjazz** [comment]
@a-komarev I've been using my fork ever since, its' been working great so far, I'll switch over to yours now that this is merged and test some more.

**Comment by antonkomarev** [comment]
It's merged but not yet published release, so only dev-master is usable. I'd recommend to wait a final release. I need to test this feature myself and will be able to do it only in November.

**Comment by acidjazz** [comment]
@a-komarev sounds good!

**Comment by antonkomarev** [comment]
Thanks Kevin! I've published new release with improved check if model was liked\disliked. All details could be found in #32.
