### ISSUE TITLE
weird issue when deleting a mongodb model

### ISSUE THREAD

**Issue by vesper8** [cybercog/laravel-likeable#29]
Not sure what's the problem here. Using latest version of your package, I prepared my model which is a mongodb model with hybrid relations to mysql models

I didn't actually do anything else with your package in this project yet.. I'm not using it yet.

If I try to do something as simple as delete-> or forceDelete() the model with the likeable trait I get this weird error
```
Type error: Argument 1 passed to Cog\Likeable\Observers\ModelObserver::deleted() must be an instance of Cog\Likeable\Contracts\Likeable, instance of App\Models\MyModel given
```

Where MyModel is the model I'm trying to delete. Not doing anything special here:

```
$submissions = Submission::has('media', '=', 0)->get();
        d("Deleting " . $submissions->count() . "submissions with no media attached");

        foreach ($submissions as $submission) {
            $submission->forceDelete();
        }
```

Any ideas?

**Comment by antonkomarev** [comment]
Hello @vesper8! Did you defined that your model implements Likeable contract?

```php
namespace App\Models;

use Cog\Likeable\Contracts\Likeable as LikeableContract;

class MyModel extends Model implements LikeableContract
{
}
```

[Example in documentation](https://github.com/cybercog/laravel-likeable#prepare-likeable-model)

**Comment by vesper8** [comment]
no I hadn't, I thought that was optional

Anyway just trying it now, I see that if you implement that then you have to add several methods to the class?

Anyway I wasn't using it, only the likeable trait

**Comment by antonkomarev** [comment]
This is strict requirement, to be sure that your model implements all required methods. If you implement it, then yes you are required to implement all the methods defined in the interface or just use packaged trait.
This allows you to change Likeable implementation without worrying that package wouldn't work.

**Comment by antonkomarev** [comment]
Closing this issue because its looks like solved. Feel free to reopen it or continue conversation.

**Comment by vesper8** [comment]
@a-komarev sorry I didn't see your reply for some reason.

Like I said, I had *not* implemented it. Isn't it optional? I know if I do implement it then I need to add the methods. But if I don't?

I think I stumbled upon a real problem with mongodb maybe?

I am still having the same problem if I only use Likeable trait.

Documentation seems to point that implementing the contract is optional
`Use Likeable contract in model which will get likes behavior and implement it or just use Likeable trait.`

Anyway I did go ahead and added the contract, which forced me to declare two methods: getKey and getMorphClass. I had no idea what to put in there but eventually I managed to get my deletions to work properly by adding these:

```
    public function getKey() {
        return parent::getKey();
    }

    public function getMorphClass() {
        return parent::getMorphClass();
    }
```

**Comment by antonkomarev** [comment]
Defining that your model implements Likeable contract (interface) is strict requirement. Implementing all methods required by the interface is mandatory because PHP won't work without it (will stop execution with fatal error). [More info about PHP interfaces in official documentation](http://php.net/manual/en/language.oop5.interfaces.php).

To simplify developers life I've added default implementation as Likeable trait. Trait doesn't include `getKey` and `getMorphClass` methods because it's designed for Eloquent models and Eloquent Model class already has both of these methods.

If you are OK with default behavior and extending Eloquent Model - just define that your model implements Likeable contract and use Likeable trait and you are ready to go. There is no need to do anything else in your model then.

**Comment by vesper8** [comment]
Right.. but since I am using a mongodb model, it seems like getKey and getMorphClass were not defined by default.. so I needed to add them and was a bit puzzled what the values should be.. anyway I hope my experience can help someone else some day. Now it works well with mongodb model

**Comment by antonkomarev** [comment]
But if you defined `getKey` and `getMorphClass` this way:

```php
    public function getKey() {
        return parent::getKey();
    }

    public function getMorphClass() {
        return parent::getMorphClass();
    }
```
That means that this methods already implemented by parent model, and this definitions will do nothing.
