### ISSUE TITLE
Deleting a likeable model causes a SQL error

### ISSUE THREAD

**Issue by acidjazz** [cybercog/laravel-likeable#30]
I'm not 100% sure the problem is this package, but when I delete a row from a Likeable model using `->delete()` I get this error:

SQLSTATE[22007]: Invalid datetime format: 1292 Truncated incorrect DOUBLE value: '1103d0bbff0e942fdf0d542e818f8ae2f88ba05d' (SQL: delete from `like` where (`likeable_id` = 102 and `likeable_type` = App\Models\Scene and `type_id` = like))

In my case I have id's in my DB that are hashes instead of just integers/floats.

**Comment by antonkomarev** [comment]
Why it's arguing on DOUBLE value and said that it's invalid datetime format?

**Comment by antonkomarev** [comment]
Closing due inactivity. Feel free to continue conversation if problem still exists.
