### ISSUE TITLE
My Article not Likeable anymore

### ISSUE THREAD

**Issue by imsidz** [cybercog/laravel-likeable#31]
hi when i try to like article getting problem
Type error: Argument 1 passed to Cog\Likeable\Services\LikeableService::addLikeTo()

**Comment by antonkomarev** [comment]
Hello, @imsidz.
You haven't provided full debug, but I suppose that `addLikeTo` method receiving `null` or `Article` instance without implemented `\Cog\Likeable\Contracts\Likeable` interface.

Could you provide more information? Does your `Article` model implements `Likeable` interface?
Here is [how Likeable model should be prepared](https://github.com/cybercog/laravel-likeable#prepare-likeable-model).

**Comment by imsidz** [comment]
i am trying to add likeable to movies model
here is model

```
<?php

namespace App;

use Ghanem\Rating\Traits\Ratingable as Rating;
use Nicolaslopezj\Searchable\SearchableTrait;
use Illuminate\Database\Eloquent\Model;
use Cog\Likeable\Contracts\Likeable as LikeableContract;
use Cog\Likeable\Traits\Likeable;

class Movie extends Model
{   

    use Likeable;
    use SearchableTrait;
    use Rating;
```

here is controller

```
public function movielike($movie){
    	$movie = Movie::where('slug', $movie)->firstorfail();
        $movie->like();
        /**
        $user = Auth::user();
        $reward = 5;
        $currentreward = $user->reward;
        $user->reward = $currentreward + $reward;
        $user->save();
        **/
        return Redirect::back()->with('status', 'like Success');
    }
```

i think i am using same like documentation

**Comment by antonkomarev** [comment]
@imsidz you've forgot to implement contract for `Movie` model.

```php
<?php

namespace App;

use Ghanem\Rating\Traits\Ratingable as Rating;
use Nicolaslopezj\Searchable\SearchableTrait;
use Illuminate\Database\Eloquent\Model;
use Cog\Likeable\Contracts\Likeable as LikeableContract;
use Cog\Likeable\Traits\Likeable;

class Movie extends Model implements LikeableContract
{   

    use Likeable;
    use SearchableTrait;
    use Rating;
```

Just add `implements LikeableContract` after `extends Model` and it should work.

**Comment by imsidz** [comment]
Ohh Lol I Really Sorry For that its working fine after implements 

thank you for making this dependency its more help full

hope you can rating system or reward system

thanks anyway

**Comment by antonkomarev** [comment]
Glad it's working!

We have rating system and awards packages but they are not open source yet. Maybe in near future :wink:
